version: '3.8'
services:
  flask-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    networks:
      - my-react-app-network

  react-frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
    networks:
      - my-react-app-network

  postgres:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flask
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - my-react-app-network

  locust:
    build:
      context: .
      dockerfile: locust/Dockerfile
    environment:
      - TARGET_URL=http://flask-backend:5000
    ports:
      - "8089:8089"
    networks:
      - my-react-app-network

networks:
  my-react-app-network: